import { autoGeneratedHashKey, versionAttribute, table, attribute } from '@aws/dynamodb-data-mapper-annotations'

@table('City')
export class City {
  @autoGeneratedHashKey()
  id: string

  @attribute()
  name: string

  @attribute()
  state: string

  @versionAttribute()
  version: number
}
