import { autoGeneratedHashKey, versionAttribute, table, attribute } from '@aws/dynamodb-data-mapper-annotations'

@table('User')
export class User {
  @autoGeneratedHashKey()
  id:string

  @attribute()
  fullName:string

  @attribute()
  gender: string

  @attribute()
  birthday: string

  @attribute()
  cityId: string

  @versionAttribute()
  version:number

  getAge (): number {
    if (this.birthday) {
      const year = (new Date()).getFullYear()
      const [, , yearBirthday] = this.birthday.split('/')
      const age = year - (+yearBirthday)
      return age
    }
    return 0
  }
}
